name: Build Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build_feature:
    name: Build Examples
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            name: linux

          - os: macos-latest
            name: mac

          - os: windows-latest
            name: win

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build Example Harness
        run: |
          cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Debug -DSST_EFFECTS_BUILD_EXAMPLES=TRUE -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
          cmake --build ./build --config Debug --target voice-effect-example

